# Generated by Django 6.0.5 on 2026-05-06 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carta_nombre', models.CharField(max_length=100)),
                ('contenido', models.TextField()),
            ],
        ),
    ]
